# Generated by Django 5.1 on 2024-11-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_discountoffer_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountoffer',
            name='status',
            field=models.CharField(choices=[('blocked_offer', 'Blocked Offer'), ('inactive_offer', 'Inactive Offer')], default='inactive_offer', max_length=20),
        ),
    ]
