# Generated by Django 5.1 on 2024-11-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_discountoffer_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='discountoffer',
            constraint=models.UniqueConstraint(fields=('account_number', 'discount_offer', 'status'), name='unique_blocked_offer_discount'),
        ),
    ]
